hpc = read.csv(file="household_power_consumption.txt",head=TRUE,sep=";")
hpc07 <- hpc[(hpc$Date == "1/2/2007") | (hpc$Date == "2/2/2007"),]
datetime = paste(hpc07$Date,hpc07$Time)
hpc07$DateTime = strptime(datetime,"%d/%m/%Y %H:%M:%S")
write.csv(hpc07,file="hpc07.txt",row.names=FALSE)
par(mfrow=c(2,2))
plot(hpc07$DateTime, hpc07$Global_active_power, type="l", xlab="", ylab="Global Active Power (kilowatts)")
hpc07$Voltage = as.numeric(as.character(hpc07$Voltage))
plot(hpc07$DateTime, hpc07$Voltage, type="l", xlab="datetime", ylab="Voltage")
plot(hpc07$DateTime, hpc07$Sub_metering_1, type="l", xlab="", ylab="Energy sub metering")
lines(hpc07$DateTime, hpc07$Sub_metering_2, type="l", col="red")
lines(hpc07$DateTime, hpc07$Sub_metering_3, type="l", col="blue")
legend("topright", lty=1, lwd=1, col=c("black","blue","red"), legend=labels)
hpc07$Global_reactive_power=as.numeric(as.character(hpc07$Global_reactive_power))
plot(hpc07$DateTime, hpc07$Global_reactive_power, type = "l", xlab="datetime", ylab="Global reactive power")        
dev.copy(png,file="plot4.png",width=480,height=480)
dev.off()